apiVersion: v2
name: k8s-node-dns
version: 1.0.0
description: >
  A Kubernetes controller that serves DNS A/AAAA records, which resolve
  to the external IPs of all ready nodes in user-defined areas.
type: application
home: https://github.com/ds8088/k8s-node-dns
sources:
  - https://github.com/ds8088/k8s-node-dns
maintainers:
  - name: ds8088
    url: https://pootis.network
appVersion: 1.0.15
