apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-node-dns.fullname" . }}
  labels:
    {{- include "k8s-node-dns.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
