{{- if .Values.config.leaderElect }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-node-dns.roleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-node-dns.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
{{- end }}
