apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-node-dns.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-node-dns.labels" . | nindent 4 }}
